services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-dev
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_dev:/data/db
    networks:
      - mern-network-dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-dev
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run start
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_NAME=boilerplate_db
      - DATABASE_DEV=mongodb://mongodb:27017/<DATABASE>
      - JWT_SECRET=local-development-jwt-secret-key
      - JWT_EXPIRES_IN=90d
      - JWT_COOKIE_EXPIRES_IN=90
      - EMAIL_FROM_NAME=MERN Boilerplate
      - EMAIL_FROM_ADDRESS=noreply@localhost
    networks:
      - mern-network-dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend-dev
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - VITE_API_URL=http://localhost:3000/api/v1
      - VITE_APP_NAME=MERN Boilerplate
    networks:
      - mern-network-dev

networks:
  mern-network-dev:
    driver: bridge

volumes:
  mongodb_data_dev:
